### ISSUE TITLE
how to stop job?

### ISSUE THREAD

**Issue by pondered** [Pool-Of-Tears/KtScheduler#22]

**Comment by pondered** [comment]
if job is running, how to stop it

**Comment by starry-shivam** [comment]
> if job is running, how to stop it

http://javadoc.jitpack.io/com/github/Pool-Of-Tears/KtScheduler/1.1.5/javadoc/-kt-scheduler/dev.starry.ktscheduler.scheduler/-scheduler/pause-job.html?query=abstract%20fun%20pauseJob
